### ISSUE TITLE
Getting container name is broken when using docker 1.10.1

### ISSUE THREAD

**Issue by thrucker** [bwalex/fluent-plugin-docker-format#5] opened 2016-02-19 14:44 UTC
The name of the container config JSON file seems to have changed as of docker 1.10.1. It's now called `config.v2.json`. See https://github.com/bwalex/fluent-plugin-docker-format/blob/master/lib/fluent/plugin/out_docker_format.rb#L41

**Comment by meetyg** [comment] 2016-04-03 04:23
Hi there Alex. 
I like your plugin, especially because it doesn't need a connection to Docker engine.
The problem is that it doesn't work with Docker 1.10 and above as mentioned.
When do you think this will be solved, and PR will be merged?

**Comment by ermaker** [comment] 2016-04-03 04:38
@bwalex 
I also hope that #6 is merged.

**Comment by bwalex** [comment] 2016-04-03 14:04
Sorry, I dropped the ball on this - all merged now. Thanks!

**Closed** 2016-04-03 14:03 UTC
